src/Entity/Company.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompanyRepository")
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $mobile_phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activity;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active = 1;



    public function __construct()
    {
        $this->Stages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getMobilePhone(): ?string
    {
        return $this->mobile_phone;
    }

    public function setMobilePhone(?string $mobile_phone): self
    {
        $this->mobile_phone = $mobile_phone;

        return $this;
    }

    public function getActivity(): ?string
    {
        return $this->activity;
    }

    public function setActivity(?string $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use Doctrine\DBAL\DBALException;
use Doctrine\DBAL\Driver\PDOException;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CompanyController extends AbstractController
{
    /**
     * @Route("/company/show", name="show_companies")
     */
    public function showAll()
    {

        # Get the repo
        $repo = $this->getDoctrine()->getRepository(Company::class);

        # Get All companies
        $companies = $repo->findAll();

        return $this->render('company/index.html.twig', [
            'companies' => $companies,
        ]);
    }

    /**
     * @Route("/company/add", name="add_company")
     */
    public function addCompany(Request $request)
    {

        # create a empty company
        $company = new Company();

        # Build the from
        $formBuild = $this->createFormBuilder($company)
            ->add('name', TextType::class)
            ->add('city', TextType::class)
            ->add('postal_code', TextType::class)
            ->add('address', TextType::class)
            ->add('mail', TextType::class)
            ->add('mobile_phone', TextType::class)
            ->add('activity', TextType::class);

        # Getting the form

        $formBuild->add('create', SubmitType::class, array("label" => "Add company"));

        $form = $formBuild->getForm();

        $form->handleRequest($request);

        # If the form is submitted
        if ($form->isSubmitted() && $form->isValid()) {
            $product_data = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();

            // tell Doctrine you want to (eventually) save the Product (no queries yet)
            $entityManager->persist($product_data);
            // actually executes the queries (i.e. the INSERT query)
            $entityManager->flush();

            return $this->redirectToRoute('show_companies');
        }else{
            return $this->render('company/addCompany.html.twig',
                array( 'form' => $form->createView(), 'tab' => array('name','city','postal_code','address','mail','mobile_phone','activity')));
        }
    }



    /**
     * @Route("/admin/company/edit/{id}", name="company_edit")
     */
    public function edit($id, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $company = $entityManager->getRepository(Company::class)->find($id);
        $form = $this->createFormBuilder($company)
            ->add('name', TextType::class)
            ->add('city', TextType::class)
            ->add('postal_code', TextType::class)
            ->add('address', TextType::class)
            ->add('mail', TextType::class)
            ->add('mobile_phone', TextType::class)
            ->add('activity', TextType::class)
            ->add('create', SubmitType::class, array("label" => "Edit"))
            ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $company = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($company);
            $entityManager->flush();
            return $this->redirectToRoute('show_companies');
        }
        return $this->render('company/edit.html.twig', array(
            'form' => $form->createView()));
    }

    /**
     * @Route("/admin/product/delete/{id}", name="company_delete")
     */
    public function delete($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $company = $entityManager->getRepository(Company::class)->find($id);

        try {
            $entityManager->remove($company);
            $entityManager->flush();
        }catch (ForeignKeyConstraintViolationException $e){
            $this->addFlash("danger", "Erreur ! Vous ne pouvez pas supprimer cette entreprise car elle est déjà liée à un stage.".$e->getMessage());
            return $this->redirectToRoute("show_companies");
        }


        return $this->redirectToRoute('show_companies');
    }







}

templates/company/addCompany.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-4 main">
        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Ajouter une entreprise

                        <span class="pull-right clickable panel-toggle panel-button-tab-left"><em
                                    class="fa fa-toggle-up"></em></span></div>
                    <div class="panel-body">

                        {{ form_start(form) }}


                        <div class="form-group">
                            {{ form_label(form.name) }}
                            {{ form_errors(form.name) }}
                            {{ form_widget(form.name,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.city) }}
                            {{ form_errors(form.city) }}
                            {{ form_widget(form.city,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.postal_code) }}
                            {{ form_errors(form.postal_code) }}
                            {{ form_widget(form.postal_code,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.address) }}
                            {{ form_errors(form.address) }}
                            {{ form_widget(form.address,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.mail) }}
                            {{ form_errors(form.mail) }}
                            {{ form_widget(form.mail,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.mobile_phone) }}
                            {{ form_errors(form.mobile_phone) }}
                            {{ form_widget(form.mobile_phone,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.activity) }}
                            {{ form_errors(form.activity) }}
                            {{ form_widget(form.activity,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div><!--/.row-->
    </div>
    </div{% endblock %}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-4 main">
        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Modifier une entreprise

                        <span class="pull-right clickable panel-toggle panel-button-tab-left"><em
                                    class="fa fa-toggle-up"></em></span></div>
                    <div class="panel-body">

                        {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.name) }}
                            {{ form_errors(form.name) }}
                            {{ form_widget(form.name,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.city) }}
                            {{ form_errors(form.city) }}
                            {{ form_widget(form.city,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.postal_code) }}
                            {{ form_errors(form.postal_code) }}
                            {{ form_widget(form.postal_code,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.address) }}
                            {{ form_errors(form.address) }}
                            {{ form_widget(form.address,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.mail) }}
                            {{ form_errors(form.mail) }}
                            {{ form_widget(form.mail,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.mobile_phone) }}
                            {{ form_errors(form.mobile_phone) }}
                            {{ form_widget(form.mobile_phone,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.activity) }}
                            {{ form_errors(form.activity) }}
                            {{ form_widget(form.activity,{'attr': {'class': 'form-control'}}) }}
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div><!--/.row-->
    </div>
    </div{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    <div class="col-sm-9 col-sm-offset-3 col-lg-15 col-lg-offset-2 main">
        <div class="centered_panel">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Liste de toutes les entreprises
                        </div>
                        <div class="panel-body">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                <tr>
                                    <th>Nom</th>
                                    <th>Ville</th>
                                    <th>Adresse</th>
                                    <th>Code postal</th>
                                    <th>Mail</th>
                                    <th>Téléphone portable</th>
                                    <th>Activité</th>
                                    <th>Est active ?</th>
                                    {% if is_granted('ROLE_ADMIN') %}
                                    <th>Modifier</th>
                                    <th>Supprimer</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% for company in companies %}
                                    <tr>
                                        <td>{{ company.name }}</td>
                                        <td>{{ company.city }}</td>
                                        <td>{{ company.address }}</td>
                                        <td>{{ company.postalCode }}</td>
                                        <td>{{ company.mail }}</td>
                                        <td>{{ company.mobilePhone }}</td>
                                        <td>{{ company.activity }}</td>
                                        <td>{% if company.isActive == 1 %}yes{% else %}no{% endif %}</td>
                                        {% if is_granted('ROLE_ADMIN') %}
                                        <td><a class="" href="{{ path('company_edit', {'id': company.id}) }}"><span class="fa fa-edit">&nbsp;</span></a></td>
                                        <td><a class="" href="{{ path('company_delete', {'id': company.id}) }}"><span class="fa fa-trash">&nbsp;</span></a></td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>

                            </table>
                            <a class="" href="{{ path('add_company') }}">
                                <span class="fa fa-arrow-right">&nbsp;</span> Add a Company
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}