src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 */
class Users implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }


    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank()
     */
    private $login;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $name;


    /**
     * The below length depends on the "algorithm" you use for encoding
     * the password, but this works well with bcrypt.
     *
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=250)
     */
    private $plainPassword;


    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;


    /**
     * @ORM\Column(name="roles", type="array")
     */
    private $roles = array();

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $lastname;

    public function __construct()
    {
        $this->isActive = true;
        $this->Stages = new ArrayCollection();
// may not be needed, see section on salt below
// $this->salt = md5(uniqid('', true));
    }

    public function getUsername()
    {
        return $this->login;
    }

    public function getSalt()
    {
// you *may* need a real salt depending on your encoder
// see section on salt below
        return null;
    }

    public function getPassword()
    {
        return $this->password;
    }

    function setPassword($password)
    {
        $this->password = $password;
    }

    public function getRoles()
    {
        if (empty($this->roles)) {
            return ['ROLE_USER'];
        }
        return $this->roles;
    }

    function addRole($role)
    {
        $this->roles[] = $role;
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->login,
            $this->password,
            $this->isActive,
// see section on salt below
// $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->login,
            $this->password,
            $this->isActive,
// see section on salt below
// $this->salt
            ) = unserialize($serialized);
    }

    function getIsActive()
    {
        return $this->isActive;
    }

    function getPlainPassword()
    {
        return $this->plainPassword;
    }

    function setId($id)
    {
        $this->id = $id;
    }

    function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;
    }
    function setIsActive($isActive)
    {
        $this->isActive = $isActive;
    }

    /**
     * @return mixed
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * @param mixed $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}EasyStage !{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-table.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-theme.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/datepicker.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/datepicker3.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/font-awesome.min.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/my-css.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/css/dataTables.bootstrap.min.css') }}"/>
        <link rel="stylesheet" href="{{ asset('assets/sass/styles.scss') }}"/>
    {% endblock %}

    {% block header %}
    <link rel="shortcut icon" href="{{ asset('assets/images/profilePic.icon') }}">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ path('index') }}"><span>Easy</span>Stage</a>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <div class="profile-sidebar">
                <div class="profile-userpic">
                    <img src="{{ asset('assets/images/profilePic.png') }}" class="img-responsive" alt="">
                </div>

                <div class="profile-usertitle">
                    <div class="profile-usertitle-name"><a href="{{ path('show_profile') }}">{{ app.user.username }}</a>
                    </div>
                    <div class="profile-usertitle-status"><span class="indicator label-success"></span>En ligne</div>
                </div>

                <div class="clear"></div>
            </div>
            <div class="divider"></div>{% endif %}
        <ul class="nav menu">
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                <li class="active"><a href="{{ path('index') }}"><em class="fa fa-dashboard">&nbsp;</em> Page D'accueil</a></li>
                <li class="parent "><a data-toggle="collapse" href="#sub-item-1">
                        <em class="fa fa-navicon">&nbsp;</em> Entreprises <span data-toggle="collapse" href="#sub-item-1"
                                                                              class="icon pull-right"><em
                                    class="fa fa-plus"></em></span>
                    </a>
                    <ul class="children collapse" id="sub-item-1">
                        <li><a class="" href="{{ path('show_companies') }}">
                                <span class="fa fa-arrow-right">&nbsp;</span> Liste des entreprises
                            </a></li>
                        <li><a class="" href="{{ path('add_company') }}">
                                <span class="fa fa-arrow-right">&nbsp;</span> Ajouter une entreprise
                            </a></li>
                    </ul>
                </li>
                {% if is_granted("ROLE_ADMIN") %}
                    <li><a href="{{ path('adminShowUsers') }}"><em class="fa fa-user-o"></em> Gestion des utilisateurs</a></li>
                {% elseif is_granted("ROLE_STUDENT") %}
                    <li><a href="{{ path('eleve_stage') }}"><em class="fa fa-address-card">&nbsp;</em> Stages</a></li>
                {% elseif is_granted("ROLE_PROFESSOR") or is_granted("ROLE_ADMIN") %}
                    <li class="parent "><a data-toggle="collapse" href="#stagesMenu">
                            <em class="fa fa-address-card"></em> Stages <span data-toggle="collapse" href="#stagesMenu"
                                                                             class="icon pull-right"><em
                                        class="fa fa-plus"></em></span>
                        </a>
                        <ul class="children collapse" id="stagesMenu">
                            <li><a class="" href="{{ path('showAllStages') }}">
                                    <span class="fa fa-arrow-right">&nbsp;</span> Liste des stages
                                </a></li>
                            <li><a class="" href="{{ path('usersWithoutStage') }}">
                                    <span class="fa fa-arrow-right">&nbsp;</span> Elèves sans stages
                                </a></li>
                        </ul>
                    </li>
                    <li><a href="{{ path('showReferredStudent') }}"><em class="glyphicon glyphicon-list">&nbsp;</em>Elèves référencés</a></li>
                {% endif %}
                <li><a href="{{ path('logout') }}"><em class="fa fa-power-off">&nbsp;</em> Déconnexion</a></li>
            {% else %}
                <li><a href="{{ path('login') }}"><em class="fa fa-power-off">&nbsp;</em>Connexion</a></li>
                <li><a href="{{ path('inscription') }}"><em class="fa fa-sign-in">&nbsp;</em>Inscription</a></li>
            {% endif %}

        </ul>
    </div><!--/.sidebar-->


    {#Handling flash messages#}
    <div class="container">
        <div class="col-sm-9 col-sm-offset-3 col-lg-12 col-lg-offset-4 main">
            <div class="centered_panel">
                <div class="row">
                    <div class="col-md-5">
                        {% for label, messages in app.flashes %}
                            {% for message in messages %}
                                <div class="alert alert-{{ label }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</head>


</head>
<body>
{% block body %}


{% endblock %}
{% block javascripts %}
    <script src="{{ asset('assets/js/jquery-1.11.1.min.js') }}"></script>
    <script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/chart.min.js') }}"></script>
    <script src="{{ asset('assets/js/easypiechart.js') }}"></script>
    <script src="{{ asset('assets/js/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('assets/js/custom.js') }}"></script>
    <script src="{{ asset('assets/js/jquery-3.3.1.js') }}"></script>
    <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/js/dataTables.bootstrap.min.js') }}"></script>
    <script>

    </script>

{% endblock %}

</body>
</html>